# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

default: &default
  working_directory: ~/project
  docker:
    - image: circleci/node:latest

require_frame: &require_frame
  requires:
    - frame

jobs:
  frame:
    <<: *default
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - df:10:f6:55:bb:04:b7:11:37:5f:4c:cf:57:f3:f4:5d
      - run: ssh-keyscan github.com dota2wiki.duduluu.com >> ~/.ssh/known_hosts
      - restore_cache:
          keys:
            - v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-{{ .Branch }}-
            - v1-
      - run: yarn --network-timeout 600000
      - save_cache:
          paths:
            - node_modules/
            - ~/.cache
          key: v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: yarn void-ui
      - run: yarn build
      - persist_to_workspace:
          root: ~/
          paths:
            - project
            - .ssh

  build-gh-pages:
    <<: *default
    steps:
      - attach_workspace:
          at: ~/

      - run: yarn --cwd packages/dota2wiki build:gh-pages
      - run: yarn --cwd packages/dota2wiki copy-i18n
      - run: yarn --cwd packages/dota2wiki gen-pages
      - run:
          name: deploy to dota2wiki.github.io
          working_directory: packages/dota2wiki/dist
          command: |
            git init
            git config user.email dota2wiki@outlook.com
            git config user.name dota2wiki-bot
            git remote add origin git@github.com:dota2wiki/dota2wiki.github.io.git
            git add .
            git commit -m "auto deploy"
            git push origin master --force

  build-cloud:
    <<: *default
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn --cwd packages/dota2wiki build:cloud
      - run: yarn --cwd packages/dota2wiki copy-i18n
      - run:
          name: deploy to dota2wiki.duduluu.com
          command: |
            sudo apt install rsync
            rsync -avr packages/dota2wiki/dist/* ubuntu@dota2wiki.duduluu.com:/var/sites/dota2wiki.duduluu.com
            scp packages/dota2wiki/dist/* ubuntu@dota2wiki.duduluu.com:/var/sites/dota2wiki.duduluu.com

  build-huiji:
    <<: *default
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn --cwd packages/dota2wiki build:huiji
      - run: yarn --cwd packages/dota2wiki copy-i18n
      - run:
          name: deploy to dota2.huijiwiki.com
          command: |
            sudo apt install rsync
            rsync -avr packages/dota2wiki/dist/* ubuntu@dota2wiki.duduluu.com:/var/sites/dota2.huijiwiki.com
            scp packages/dota2wiki/dist/* ubuntu@dota2wiki.duduluu.com:/var/sites/dota2.huijiwiki.com

workflows:
  version: 2
  workflow:
    jobs:
      - frame:
          filters:
            branches:
              only:
                - master
      - build-gh-pages:
          requires:
            - frame
          filters:
            branches:
              only: master
      - build-cloud:
          requires:
            - frame
          filters:
            branches:
              only: master
      - build-huiji:
          requires:
            - frame
          filters:
            branches:
              only: master
